version: '3.8'
services:
  nextia-api:
    container_name: api-nextia
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4002:4002'
    networks:
      - nextia-network
    depends_on:
      - mongo
      - redis
    environment:
      NODE_ENV: production
      SECRET_JWT: ${SECRET_JWT_PRODUCTION}
      PORT: 4002
      MONGO_URL: ${MONGO_URL_PRODUCTION}
      REDIS_URL: ${REDIS_URL_PRODUCTION}

  mongo:
    container_name: mongo
    image: mongo:4.4.0-rc7-bionic
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${USER_NAME_DB}
      - MONGO_INITDB_ROOT_PASSWORD=${PASSWORD_DB}
      - MONGO_INITDB_DATABASE=nextia
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - /home/developer/nextia/data:/data/db
    networks:
      - nextia-network
    command: mongod --logpath=/dev/null
    ports:
      - '27017:27017'

  redis:
    container_name: redis-nextia
    image: redis:alpine
    networks:
      - nextia-network
    command: redis-server --appendonly yes --requirepass ${PASSWORD_DB}
    ports:
      - '6379:6379'

networks:
  nextia-network:
    driver: bridge
